--- HOST: http://www.google.com/

--- wideor-server ---
An API to create videos from images
---

---

--
Video resource 
--

List products added into your shopping-cart. (comment block again in Markdown)
GET /api/videos/{id}
< 200
< Content-Type: application/json
{ 
    "id": ,
    "duration": 1,
    "format": "",
    "status": "",
    "data": {
        
    },
    "result": {} 
}

A valid and created video
GET /api/videos/1234
< 200
< Content-Type: application/json
{ 
    "id": ,
    "duration": 1,
    "format": "",
    "status": "",
    "data": {
        
    },
    "result": {} 
}

A video in the waiting queue
GET /api/videos/1235
< 200
< Content-Type: application/json
{ 
    "id": ,
    "duration": 1,
    "format": "",
    "status": "",
    "data": {
        
    },
    "result": {} 
}

A video in progress
GET /api/videos/1236
< 200
< Content-Type: application/json
{ 
    "id": ,
    "duration": 1,
    "format": "",
    "status": "",
    "data": {
        
    },
    "result": {} 
}

A failed video
GET /api/videos/1237
< 200
< Content-Type: application/json
{ 
    "id": ,
    "duration": 1,
    "format": "",
    "status": "",
    "data": {
        
    },
    "result": {} 
}

An non existing file
GET /api/videos/9999
< 404
< Content-Type: application/json
{ 
    "code": 404,
    "message": "Video not found"
}

Save a new video
POST /api/videos{?size}
> Content-Type: application/json
{}
< 201
< Content-Type: application/json
{}

